#!/usr/bin/env bash

# check docker image for building
if [ "$(docker images -q electron-httpp-bld:12.x 2> /dev/null)" == "" ]; then
  echo "Build Docker image as electron-httpp-bld:12.x"
  docker image build --compress -t electron-httpp-bld:12.x -f ./Dockerfile.bld .
fi

# create install dir
mkdir -p appins 

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  electron-httpp-bld:12.x $@
else
  echo "Start building ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  electron-httpp-bld:12.x bash -c "./configure --prefix=./appins/ && make -j 6 && make install"
fi
